---
- hosts: control-plane, worker*
  become: yes
  gather_facts: yes
  roles:
    - extrapkgs
    - crio
    - kubernetes

- hosts: database
  become: yes
  gather_facts: no
  roles:
    - postgresql
