---
# tasks file for roles/kubernetes
#
- name: Adding Kubernetes repository key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Installing Kubernetes repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Installing Kubelet, Kubeadm and Kubectl on Control-plane
  apt:
    name: "{{item}}"
    state: present
  loop: ["kubelet","kubeadm","kubectl"]

- name: Enable Kubelet service
  systemd:
    name: kubelet
    state: started
    enabled: yes

